// This file has been generated by EWG. Do not edit. Changes will be lost!
// struct glue code

// glue code for struct `struct pg_conn'

#include<my_postgres.h>

int ewg_struct_sizeof_struct_pg_conn ()
{
	return 1;
}


// glue code for struct `struct _PQconninfoOption'

#include<my_postgres.h>

int ewg_struct_sizeof_struct__PQconninfoOption ()
{
	return sizeof (struct _PQconninfoOption);
}

char *ewg_struct_struct__PQconninfoOption_member_get_keyword(void* a_item)
{
	return ((struct _PQconninfoOption*)a_item)->keyword;
}

void ewg_struct_struct__PQconninfoOption_member_set_keyword (void* a_item, char *a_value)
{
	((struct _PQconninfoOption*)a_item)->keyword = (char*)a_value;
}

char *ewg_struct_struct__PQconninfoOption_member_get_envvar(void* a_item)
{
	return ((struct _PQconninfoOption*)a_item)->envvar;
}

void ewg_struct_struct__PQconninfoOption_member_set_envvar (void* a_item, char *a_value)
{
	((struct _PQconninfoOption*)a_item)->envvar = (char*)a_value;
}

char *ewg_struct_struct__PQconninfoOption_member_get_compiled(void* a_item)
{
	return ((struct _PQconninfoOption*)a_item)->compiled;
}

void ewg_struct_struct__PQconninfoOption_member_set_compiled (void* a_item, char *a_value)
{
	((struct _PQconninfoOption*)a_item)->compiled = (char*)a_value;
}

char *ewg_struct_struct__PQconninfoOption_member_get_val(void* a_item)
{
	return ((struct _PQconninfoOption*)a_item)->val;
}

void ewg_struct_struct__PQconninfoOption_member_set_val (void* a_item, char *a_value)
{
	((struct _PQconninfoOption*)a_item)->val = (char*)a_value;
}

char *ewg_struct_struct__PQconninfoOption_member_get_label(void* a_item)
{
	return ((struct _PQconninfoOption*)a_item)->label;
}

void ewg_struct_struct__PQconninfoOption_member_set_label (void* a_item, char *a_value)
{
	((struct _PQconninfoOption*)a_item)->label = (char*)a_value;
}

char *ewg_struct_struct__PQconninfoOption_member_get_dispchar(void* a_item)
{
	return ((struct _PQconninfoOption*)a_item)->dispchar;
}

void ewg_struct_struct__PQconninfoOption_member_set_dispchar (void* a_item, char *a_value)
{
	((struct _PQconninfoOption*)a_item)->dispchar = (char*)a_value;
}

int ewg_struct_struct__PQconninfoOption_member_get_dispsize(void* a_item)
{
	return ((struct _PQconninfoOption*)a_item)->dispsize;
}

void ewg_struct_struct__PQconninfoOption_member_set_dispsize (void* a_item, int a_value)
{
	((struct _PQconninfoOption*)a_item)->dispsize = (int)a_value;
}


// glue code for struct `struct pg_cancel'

#include<my_postgres.h>

int ewg_struct_sizeof_struct_pg_cancel ()
{
	return 1;
}


// glue code for struct `struct _IO_FILE'

#include<my_postgres.h>

int ewg_struct_sizeof_struct__IO_FILE ()
{
	return 1;
}


// glue code for struct `struct pg_result'

#include<my_postgres.h>

int ewg_struct_sizeof_struct_pg_result ()
{
	return 1;
}


// glue code for struct `struct pgNotify'

#include<my_postgres.h>

int ewg_struct_sizeof_struct_pgNotify ()
{
	return sizeof (struct pgNotify);
}

char *ewg_struct_struct_pgNotify_member_get_relname(void* a_item)
{
	return ((struct pgNotify*)a_item)->relname;
}

void ewg_struct_struct_pgNotify_member_set_relname (void* a_item, char *a_value)
{
	((struct pgNotify*)a_item)->relname = (char*)a_value;
}

int ewg_struct_struct_pgNotify_member_get_be_pid(void* a_item)
{
	return ((struct pgNotify*)a_item)->be_pid;
}

void ewg_struct_struct_pgNotify_member_set_be_pid (void* a_item, int a_value)
{
	((struct pgNotify*)a_item)->be_pid = (int)a_value;
}

char *ewg_struct_struct_pgNotify_member_get_extra(void* a_item)
{
	return ((struct pgNotify*)a_item)->extra;
}

void ewg_struct_struct_pgNotify_member_set_extra (void* a_item, char *a_value)
{
	((struct pgNotify*)a_item)->extra = (char*)a_value;
}

struct pgNotify *ewg_struct_struct_pgNotify_member_get_next(void* a_item)
{
	return ((struct pgNotify*)a_item)->next;
}

void ewg_struct_struct_pgNotify_member_set_next (void* a_item, struct pgNotify *a_value)
{
	((struct pgNotify*)a_item)->next = (struct pgNotify*)a_value;
}


// glue code for struct `PQArgBlock'

#include<my_postgres.h>

int ewg_struct_sizeof_PQArgBlock ()
{
	return sizeof (PQArgBlock);
}

int ewg_struct_PQArgBlock_member_get_len(void* a_item)
{
	return ((PQArgBlock*)a_item)->len;
}

void ewg_struct_PQArgBlock_member_set_len (void* a_item, int a_value)
{
	((PQArgBlock*)a_item)->len = (int)a_value;
}

int ewg_struct_PQArgBlock_member_get_isint(void* a_item)
{
	return ((PQArgBlock*)a_item)->isint;
}

void ewg_struct_PQArgBlock_member_set_isint (void* a_item, int a_value)
{
	((PQArgBlock*)a_item)->isint = (int)a_value;
}


// glue code for struct `struct pgresAttDesc'

#include<my_postgres.h>

int ewg_struct_sizeof_struct_pgresAttDesc ()
{
	return sizeof (struct pgresAttDesc);
}

char *ewg_struct_struct_pgresAttDesc_member_get_name(void* a_item)
{
	return ((struct pgresAttDesc*)a_item)->name;
}

void ewg_struct_struct_pgresAttDesc_member_set_name (void* a_item, char *a_value)
{
	((struct pgresAttDesc*)a_item)->name = (char*)a_value;
}

Oid ewg_struct_struct_pgresAttDesc_member_get_tableid(void* a_item)
{
	return ((struct pgresAttDesc*)a_item)->tableid;
}

void ewg_struct_struct_pgresAttDesc_member_set_tableid (void* a_item, Oid a_value)
{
	((struct pgresAttDesc*)a_item)->tableid = (Oid)a_value;
}

int ewg_struct_struct_pgresAttDesc_member_get_columnid(void* a_item)
{
	return ((struct pgresAttDesc*)a_item)->columnid;
}

void ewg_struct_struct_pgresAttDesc_member_set_columnid (void* a_item, int a_value)
{
	((struct pgresAttDesc*)a_item)->columnid = (int)a_value;
}

int ewg_struct_struct_pgresAttDesc_member_get_format(void* a_item)
{
	return ((struct pgresAttDesc*)a_item)->format;
}

void ewg_struct_struct_pgresAttDesc_member_set_format (void* a_item, int a_value)
{
	((struct pgresAttDesc*)a_item)->format = (int)a_value;
}

Oid ewg_struct_struct_pgresAttDesc_member_get_typid(void* a_item)
{
	return ((struct pgresAttDesc*)a_item)->typid;
}

void ewg_struct_struct_pgresAttDesc_member_set_typid (void* a_item, Oid a_value)
{
	((struct pgresAttDesc*)a_item)->typid = (Oid)a_value;
}

int ewg_struct_struct_pgresAttDesc_member_get_typlen(void* a_item)
{
	return ((struct pgresAttDesc*)a_item)->typlen;
}

void ewg_struct_struct_pgresAttDesc_member_set_typlen (void* a_item, int a_value)
{
	((struct pgresAttDesc*)a_item)->typlen = (int)a_value;
}

int ewg_struct_struct_pgresAttDesc_member_get_atttypmod(void* a_item)
{
	return ((struct pgresAttDesc*)a_item)->atttypmod;
}

void ewg_struct_struct_pgresAttDesc_member_set_atttypmod (void* a_item, int a_value)
{
	((struct pgresAttDesc*)a_item)->atttypmod = (int)a_value;
}


// glue code for struct `struct _PQprintOpt'

#include<my_postgres.h>

int ewg_struct_sizeof_struct__PQprintOpt ()
{
	return sizeof (struct _PQprintOpt);
}

pqbool ewg_struct_struct__PQprintOpt_member_get_header(void* a_item)
{
	return ((struct _PQprintOpt*)a_item)->header;
}

void ewg_struct_struct__PQprintOpt_member_set_header (void* a_item, pqbool a_value)
{
	((struct _PQprintOpt*)a_item)->header = (pqbool)a_value;
}

pqbool ewg_struct_struct__PQprintOpt_member_get_align(void* a_item)
{
	return ((struct _PQprintOpt*)a_item)->align;
}

void ewg_struct_struct__PQprintOpt_member_set_align (void* a_item, pqbool a_value)
{
	((struct _PQprintOpt*)a_item)->align = (pqbool)a_value;
}

pqbool ewg_struct_struct__PQprintOpt_member_get_standard(void* a_item)
{
	return ((struct _PQprintOpt*)a_item)->standard;
}

void ewg_struct_struct__PQprintOpt_member_set_standard (void* a_item, pqbool a_value)
{
	((struct _PQprintOpt*)a_item)->standard = (pqbool)a_value;
}

pqbool ewg_struct_struct__PQprintOpt_member_get_html3(void* a_item)
{
	return ((struct _PQprintOpt*)a_item)->html3;
}

void ewg_struct_struct__PQprintOpt_member_set_html3 (void* a_item, pqbool a_value)
{
	((struct _PQprintOpt*)a_item)->html3 = (pqbool)a_value;
}

pqbool ewg_struct_struct__PQprintOpt_member_get_expanded(void* a_item)
{
	return ((struct _PQprintOpt*)a_item)->expanded;
}

void ewg_struct_struct__PQprintOpt_member_set_expanded (void* a_item, pqbool a_value)
{
	((struct _PQprintOpt*)a_item)->expanded = (pqbool)a_value;
}

pqbool ewg_struct_struct__PQprintOpt_member_get_pager(void* a_item)
{
	return ((struct _PQprintOpt*)a_item)->pager;
}

void ewg_struct_struct__PQprintOpt_member_set_pager (void* a_item, pqbool a_value)
{
	((struct _PQprintOpt*)a_item)->pager = (pqbool)a_value;
}

char *ewg_struct_struct__PQprintOpt_member_get_fieldSep(void* a_item)
{
	return ((struct _PQprintOpt*)a_item)->fieldSep;
}

void ewg_struct_struct__PQprintOpt_member_set_fieldSep (void* a_item, char *a_value)
{
	((struct _PQprintOpt*)a_item)->fieldSep = (char*)a_value;
}

char *ewg_struct_struct__PQprintOpt_member_get_tableOpt(void* a_item)
{
	return ((struct _PQprintOpt*)a_item)->tableOpt;
}

void ewg_struct_struct__PQprintOpt_member_set_tableOpt (void* a_item, char *a_value)
{
	((struct _PQprintOpt*)a_item)->tableOpt = (char*)a_value;
}

char *ewg_struct_struct__PQprintOpt_member_get_caption(void* a_item)
{
	return ((struct _PQprintOpt*)a_item)->caption;
}

void ewg_struct_struct__PQprintOpt_member_set_caption (void* a_item, char *a_value)
{
	((struct _PQprintOpt*)a_item)->caption = (char*)a_value;
}

char **ewg_struct_struct__PQprintOpt_member_get_fieldName(void* a_item)
{
	return ((struct _PQprintOpt*)a_item)->fieldName;
}

void ewg_struct_struct__PQprintOpt_member_set_fieldName (void* a_item, char **a_value)
{
	((struct _PQprintOpt*)a_item)->fieldName = (char**)a_value;
}


